export { astToDom } from './astToDom'
export { astToVDom } from './astToVDom'
export * as contentParser from './contentParser'
export { watchRender } from './watchRender'
export * as instruction from './instruction'
export { hashRouterExtend } from './hashRouterExtend'
export { historyRouterExtend } from './historyRouterExtend'
export { stateExtend } from './stateExtend'