export { astToDom } from './astToDom'
export { astToVDom } from './astToVDom'
export { contentReplacement, contentUpdate } from './contentReplacement'
export { watchRender } from './watchRender'
export * as instruction from './instruction'